### ISSUE TITLE
Sync Data Time - 4 Hours ahead

### ISSUE THREAD

**Issue by BASL-Webteam** [BigAppleSoftball/ratingsManager#23]
Hi,
Sync Tracker Time is 4 hours ahead - http://basl-manager.herokuapp.com/payments/admin#

I ran a Sync at 7:34 AM
When completed it read "Sync Last Run on April 24 at 11:34 AM" 

Time Zone?
Jeff

**Comment by PaigePonzeka** [comment]
We actually need to do some work around these to save some data rows for these syncs. I might only store the last five syncs or something. The Timezone issn't a huge issue (I'm wondering if it was because my laptop was in PST when I pushed the last deploy?) But I'll look into it and see if its an easy fix while I'm also removing rows.

**Comment by BASL-Webteam** [comment]
You know whats interesting is.. The Sync Time is ahead at the moment. Then when you check back, the LAST SYNC Time is correct.

SO this is not a big issue at all
